[WIP] Markdown api docs
jquery/api.qunitjs.com pull request #150
Opened 2017-03-30 00:37 UTC by leobalter

this is a very early work in progress.

I'm currently using Jekyll to generate the files because of the simplicity and it's easy to use anything else later.

Everything is minimal and needs more work.

You can check some MD files at the assert and config folders.

2017-03-30 00:40 UTC, leobalter commented
I really like the fact I can see this example on GH: https://github.com/qunitjs/api.qunitjs.com/blob/a473d76f19c278af29f069b40861231afebd68c2/assert/async.md

2017-03-30 06:19 UTC, trentmwillis commented
I'm super excited for this!

Also, looks like this will move us away from the jquery-wordpress setup (which I am excited for), does this mean we will be able to do some design updates? I've gotten feedback several times recently that the visual appearance of the documentation site is a put-off (because it looks outdated).

2017-03-30 14:58 UTC, leobalter commented
> does this mean we will be able to do some design updates?

Yes! In anyway, I'll start with the most simple implementation. I'm currently using some CSS I borrowed from http://opendesignkit.org/ and I'll try to get the pages done and loading. As soon as we have it, we can improve the docs more and more.

> I've gotten feedback several times recently that the visual appearance of the documentation site is a put-off (because it looks outdated).

The docs will look crude now, but open for any improvement :)

2017-03-30 18:26 UTC, leobalter commented
The md files for api are ready. I'll create index files for folders and start applying some style.

2017-03-30 21:56 UTC, leobalter commented
This is basically ready.

We need a few things: 

- [ ] We might also set gh-pages as the main branch
- [ ] cancel the publishing hooks.
- [ ] set dns to point to the generated pages

cc @gnarf on the api.qunitjs.com, can you help me, please?

2017-03-30 21:58 UTC, leobalter commented
to test for now: run a local `jekyll serve`

2017-03-30 22:07 UTC, aulvi commented
@leobalter How can I help?

2017-03-30 22:08 UTC, leobalter commented
@aulvi I'm sorry for the extra flag here. @gnarf might help me tomorrow but I will need to point `api.qunitjs.com` to the generated gh-pages here when this is released.

2017-03-30 22:10 UTC, aulvi commented
@leobalter No worries! Feel free to ping me direct via email tomorrow if @gnarf is unavailable, I should be wfh and am happy to help.

2017-03-30 22:26 UTC, leobalter commented
For now: http://qunitjs.github.io/api

2017-03-30 22:56 UTC, platinumazure requested changes
Just some minor changes.

2017-03-30 22:56 UTC, platinumazure commented on QUnit/only.md
> +test( "say", function( assert ) {
Would prefer this say `QUnit.test` unless a destructure is shown at the top of this sample.

2017-03-30 22:56 UTC, platinumazure commented on assert/notPropEqual.md
> +    var bar = new Foo( "1", 2, {} );
Inconsistent indentation

2017-03-30 22:56 UTC, platinumazure commented on config/QUnit.config.md
> +This object isn't actually a configuration property, but is listed here anyway, as its exported through `QUnit.config`. This gives you access to some QUnit internals at runtime. See below for an exam
s/as its exported/as it's exported

I assume this is a long-standing typo rather than anything introduced in this PR, but all the same...

2017-03-30 22:56 UTC, platinumazure commented on config/QUnit.config.md
> +By default QUnit will use whatever the starting content of `#quint-fixture` is as the fixture reset. If you do not want the fixture to be reset in between tests, set the value to `null`.
s/quint-fixture/qunit-fixture

2017-03-30 23:03 UTC, leobalter commented
Thanks @platinumazure, it should be fixed now.

2017-03-30 23:14 UTC, platinumazure approved these changes

2017-03-31 05:31 UTC, gibson042 approved these changes
WOW. :clap: I don't know if I'll have a chance for a deep dive, but I skimmed every file and this looks GREAT. The only question I have is whether you'd consider going even farther and moving it all into a `/docs` directory in the [primary repository](https://github.com/qunitjs/qunit/), which would allow QUnit PRs to form complete units encompassing both code and documentation changes. The work is already done here, so at this point it's just an organizational question—do we want a separate repository for documentation?

2017-03-31 17:09 UTC, leobalter commented
@gibson042 that's something I considered, and another reason to have md+jekyll as a +1 combo on GitHub.

We'll need to figure out how to have it in sync with the published docs, thou. That's gonna be easy anyway.

2017-03-31 18:45 UTC, merged